### ISSUE TITLE
Resolve out of range error

### ISSUE THREAD

**Issue by vbrown608** [EFForg/starttls-scanner#77]
```
scanner_1  | panic: runtime error: index out of range
scanner_1  | 
scanner_1  | goroutine 379088 [running]:
scanner_1  | github.com/EFForg/starttls-check/checker.policyMatch(0xc4201fa6f8, 0x1, 0xc4200119c7, 0x9, 0x0)
scanner_1  | 	/go/src/github.com/EFForg/starttls-check/checker/hostname.go:63 +0x19b
scanner_1  | github.com/EFForg/starttls-check/checker.hasValidName(0xc4209adb10, 0x1, 0x1, 0xc42016c220, 0x2, 0x2, 0x0)
scanner_1  | 	/go/src/github.com/EFForg/starttls-check/checker/hostname.go:77 +0x91
scanner_1  | github.com/EFForg/starttls-check/checker.checkCert(0xc4200119c7, 0x9, 0xc42027e540, 0x14, 0xc42016c220, 0x2, 0x2, 0x0, 0xc4204ca3c0, 0x0, ...)
scanner_1  | 	/go/src/github.com/EFForg/starttls-check/checker/hostname.go:195 +0x4d6
scanner_1  | github.com/EFForg/starttls-check/checker.CheckHostname.func1(0xc420019ec0, 0xc4201880a0)
scanner_1  | 	/go/src/github.com/EFForg/starttls-check/checker/hostname.go:316 +0x5f
scanner_1  | created by github.com/EFForg/starttls-check/checker.CheckHostname
scanner_1  | 	/go/src/github.com/EFForg/starttls-check/checker/hostname.go:316 +0x3d7
```

**Comment by vbrown608** [comment]
Moved to https://github.com/EFForg/starttls-check/issues/27
